name: Koha Packages Docker

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        koha_version: [19.05, 19.11]
        base_image: ['debian:stretch-slim', 'debian:buster-slim', 'bitnami/minideb:stretch', 'bitnami/minideb:buster']

    steps:
      - uses: actions/checkout@v1
      - name: Export additional variables needed by koha-testing-docker
        id: VARS
        run: |
            TMP1=${{ matrix.base_image }} && TMP2=${TMP1/:/-} && TMP3=${TMP2/\//-} && echo $TMP3
            echo ::set-output name=DOCKER_IMAGE_TAG::$TMP3

      - name: Publish to Quay.io
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bywatersolutions/koha-package-docker
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          buildoptions: "--build-arg KOHA_VERSION=${{ matrix.koha_version }} --build-arg BASE_IMAGE=${{ matrix.base_image }}"
          tags: "${{ matrix.koha_version }}-${{ steps.VARS.outputs.DOCKER_IMAGE_TAG }},${{ matrix.koha_version }}-${{ steps.VARS.outputs.DOCKER_IMAGE_TAG }}-${{ github.run_number }}"
